# Numpy Arrays & Array Properties

In [1]:
import numpy as np

In [2]:
a = np.array(range(5))
a

array([0, 1, 2, 3, 4])

In [3]:
# Create 2D Array
b = np.array([range(5), range(5)])
b

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [4]:
# Add an array with an int
b + 2

array([[2, 3, 4, 5, 6],
       [2, 3, 4, 5, 6]])

In [5]:
print(f"Shape of array a: {a.shape}   -   Shape of array b: {b.shape}")

Shape of array a: (5,)   -   Shape of array b: (2, 5)


In [6]:
print(f"Size of array a: {a.size}   -   Size of array b: {b.size}")

Size of array a: 5   -   Size of array b: 10


In [7]:
print(
    f"Number of Dimensions of array a: {a.ndim}   -   Number of Dimensions of array b: {b.ndim}"
)

Number of Dimensions of array a: 1   -   Number of Dimensions of array b: 2


In [8]:
print(f"Data Type of array a: {a.dtype}   -   Data Type of array b: {b.dtype}")

Data Type of array a: int64   -   Data Type of array b: int64


In [9]:
c = np.array(["I", "Love", "Python"])
print(f"Shape: {c.shape}\nSize: {c.size}\nndim: {c.ndim}\ndtype: {c.dtype}")

Shape: (3,)
Size: 3
ndim: 1
dtype: <U6


---

## Assignment: Array Basics

In [10]:
my_list = [x * 10 for x in range(1, 11)]
my_list

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

In [11]:
my_array = np.array(my_list)
my_array

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [12]:
print(
    f"ndim: {my_array.ndim}\nshape: {my_array.shape}\nsize: {my_array.size}\ndtype: {my_array.dtype}"
)

ndim: 1
shape: (10,)
size: 10
dtype: int64


In [13]:
my_array2 = my_array.reshape(5, 2)
my_array2

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [14]:
print(
    f"ndim: {my_array2.ndim}\nshape: {my_array2.shape}\nsize: {my_array2.size}\ndtype: {my_array2.dtype}"
)

ndim: 2
shape: (5, 2)
size: 10
dtype: int64
