# ARRAY CREATION & RANDOM NUMBER GENERATION

In [1]:
import numpy as np

---

## 1. Array Creation

### np.ones()

In [2]:
# np.ones((rows, cols), dtype)
np.ones(3)

array([1., 1., 1.])

In [3]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### np.zeros()

In [4]:
# np.zeros((rows, cols), dtype)
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.zeros((4, 4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### np.arange()

In [6]:
# np.arange(start, stop, step)
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

### np.linspace()

In [9]:
# np.linspace(start, stop, n)
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [10]:
np.linspace(10, 100, 10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [11]:
np.linspace(0, 100, 10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

### np.array.reshape()

In [12]:
# np.array.reshape(rows, cols)
a = np.arange(1, 9, 2)
a

array([1, 3, 5, 7])

In [13]:
a.reshape(2, 2)

array([[1, 3],
       [5, 7]])

---

### Laboratory Time

In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
np.ones(5, dtype=int)

array([1, 1, 1, 1, 1])

In [16]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.zeros((5, 20), dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [18]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [19]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [20]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [21]:
np.linspace(8, 64, 8)

array([ 8., 16., 24., 32., 40., 48., 56., 64.])

---

### Random Number Generation

#### np.default_rng(seed)

In [22]:
# Creates a random number generator
from numpy.random import default_rng

rng = default_rng(12345)

#### np.random(n)

In [23]:
# Returns 'n' random numbers from a uniform distribution between 0 and 1
rand_array = rng.random(10)
rand_array

array([0.22733602, 0.31675834, 0.79736546, 0.67625467, 0.39110955,
       0.33281393, 0.59830875, 0.18673419, 0.67275604, 0.94180287])

#### rng.normal(mean, stdev, n)

In [24]:
# Returns "n" random numbers from a normal distribution with a given mean and standard deviation+
rng = default_rng(42)
mean, stdev = (5, 1)

random_normal = rng.normal(mean, stdev, size=10)
random_normal

array([5.30471708, 3.96001589, 5.7504512 , 5.94056472, 3.04896481,
       3.69782049, 5.1278404 , 4.68375741, 4.98319884, 4.14695607])

In [25]:
rng = default_rng(12345)
mean, stdev = (5, 1)

random_normal = rng.normal(mean, stdev, size=10)
random_normal

array([3.57617496, 6.26372846, 4.12933826, 4.74082677, 4.92465669,
       4.25911535, 3.6322073 , 5.6488928 , 5.36105811, 3.04713694])

---


>PRO TIP: 
>
>Eventhough it's optional, make sure to **set a seed** when generating random numbers to ensure you and others can recreate the work you have done (*the value for the seed is less important*)

---

In [27]:
# A Direct Way to Generate a Seed for Random Numbers is...
# -------------------------------------------
rng = np.random.default_rng(639)
rng.random(10)
# -------------------------------------------

array([0.91171625, 0.84157988, 0.22905788, 0.75271329, 0.02463154,
       0.26137574, 0.5396075 , 0.17542692, 0.50204075, 0.26007983])

In [28]:
# Generate 100 random and integer numbers fro 0 to 10
rng.integers(0, 10, 100)

array([5, 0, 3, 1, 8, 6, 2, 5, 2, 9, 5, 3, 2, 1, 4, 0, 0, 8, 1, 8, 6, 1,
       9, 0, 2, 9, 2, 9, 5, 8, 0, 2, 1, 0, 0, 9, 6, 2, 8, 0, 7, 4, 4, 3,
       1, 6, 8, 3, 2, 0, 8, 7, 8, 1, 9, 6, 7, 4, 6, 1, 2, 3, 8, 9, 7, 4,
       6, 9, 6, 8, 1, 2, 7, 0, 9, 5, 1, 9, 8, 3, 8, 9, 3, 7, 8, 0, 8, 3,
       7, 8, 1, 5, 9, 2, 8, 9, 6, 0, 1, 2])

In [ ]:
# Generate 10 random and normally ditribute numbers
# with a Mean = 50, and a Std = 5
rng.normal(50, 5, 10)

array([52.81749392, 48.05765001, 45.61462143, 43.06442946, 48.02342603,
       45.91475553, 48.38555536, 46.41945158, 47.89898428, 58.41594894])

---

### ASSIGNMENT: Array Creation

#### Practice No.1

In [34]:
a = np.linspace(10, 100, 10)
a

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [ ]:
result_a = a.reshape(5, 2)
result_a

array([[ 10.,  20.],
       [ 30.,  40.],
       [ 50.,  60.],
       [ 70.,  80.],
       [ 90., 100.]])

In [44]:
# Another way to solve it
my_array = np.arange(10, 101, 10).reshape(5, 2)
my_array

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

#### Practice No. 2

In [41]:
n = 2022
b = np.random.default_rng(n).random(9)
b

array([0.24742606, 0.09299006, 0.61176337, 0.06066207, 0.66103343,
       0.75515778, 0.1108689 , 0.04305584, 0.41441747])

In [ ]:
result_b = b.reshape(3, 3)
result_b

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778],
       [0.1108689 , 0.04305584, 0.41441747]])

In [ ]:
# A One-Line Code Solution
np.random.default_rng(42).random(9).reshape(3, 3)

array([[0.77395605, 0.43887844, 0.85859792],
       [0.69736803, 0.09417735, 0.97562235],
       [0.7611397 , 0.78606431, 0.12811363]])