# INDEXING & SLICING ARRAYS

In [34]:
import numpy as np

In [35]:
product_array = np.array(
    [
        "fruits",
        "vegetables",
        "cereal",
        "dairy",
        "eggs",
        "snacks",
        "beverages",
        "coffe",
        "tea",
        "spices",
    ]
)
product_array

array(['fruits', 'vegetables', 'cereal', 'dairy', 'eggs', 'snacks',
       'beverages', 'coffe', 'tea', 'spices'], dtype='<U10')

In [36]:
# get 2nd item
product_array[1]

np.str_('vegetables')

In [37]:
# get last item
product_array[-1]

np.str_('spices')

In [38]:
# Slices
product_array[:5]

array(['fruits', 'vegetables', 'cereal', 'dairy', 'eggs'], dtype='<U10')

In [39]:
# more Slices with step
product_array[5::2]

array(['snacks', 'coffe', 'spices'], dtype='<U10')

---

### Slicing 2-Dimensional Array

In [40]:
product_array_2D = product_array.reshape(2, 5)
product_array_2D

array([['fruits', 'vegetables', 'cereal', 'dairy', 'eggs'],
       ['snacks', 'beverages', 'coffe', 'tea', 'spices']], dtype='<U10')

In [41]:
# Select "Coffe" - Method 1
product_array_2D[1][2]

np.str_('coffe')

In [42]:
# Select "Coffe" - Method 2
product_array_2D[1, 2]

np.str_('coffe')

In [43]:
# Now select all Rows but only the last 3 columns
product_array_2D[:, 2:]

array([['cereal', 'dairy', 'eggs'],
       ['coffe', 'tea', 'spices']], dtype='<U10')

In [44]:
# Now select only the 2nd Row with all elements
product_array_2D[1, :]

array(['snacks', 'beverages', 'coffe', 'tea', 'spices'], dtype='<U10')

---

## Laboratory: Indexing & Slicing

In [45]:
int_array = np.arange(12)
int_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [46]:
int_array[2]

np.int64(2)

In [47]:
int_array[3:-3]

array([3, 4, 5, 6, 7, 8])

In [48]:
int_array[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [49]:
int_array[::2]

array([ 0,  2,  4,  6,  8, 10])

### Reshaping Original 1D Array into a 2D Array

In [50]:
new_int = int_array.reshape(3, 4)
new_int

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [51]:
new_int[1, :]

array([4, 5, 6, 7])

In [52]:
new_int[:2, 2:]

array([[2, 3],
       [6, 7]])

In [53]:
new_int[:, :]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [54]:
new_int[2, 1]

np.int64(9)

---

## ASSIGNMENT: Indexing & Slicing

In [ ]:
assignment = np.random.default_rng(2022).random(9).reshape(3, 3)
assignment

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778],
       [0.1108689 , 0.04305584, 0.41441747]])

In [56]:
# Excercise No.1
assignment[:2, :]

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778]])

In [58]:
# Exercise No.2
assignment[:, 0]

array([0.24742606, 0.06066207, 0.1108689 ])

In [59]:
# Excercise No. 3
assignment[-1, 1]

np.float64(0.04305584439252108)