# ARRAY OPERATIONS

In [3]:
import numpy as np

In [4]:
sales = [[0, 5, 155, 0, 518], [0, 1827, 616, 317, 325]]

sales_array = np.array(sales)
sales_array

array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]])

In [5]:
# Add array + 2
sales_array + 2

array([[   2,    7,  157,    2,  520],
       [   2, 1829,  618,  319,  327]])

In [6]:
quantity = sales_array[0, :]
price = sales_array[1, :]

result = quantity * price
result

array([     0,   9135,  95480,      0, 168350])

---

## Laboratory: Array Operations

In [9]:
rng = np.random.default_rng(616)

inventory = rng.integers(0, 100, 10)
inventory

array([39, 39, 93, 86, 48, 46, 48, 30, 11, 57])

In [10]:
inventory - 24

array([ 15,  15,  69,  62,  24,  22,  24,   6, -13,  33])

In [12]:
inventory * inventory[::-1]

array([2223,  429, 2790, 4128, 2208, 2208, 4128, 2790,  429, 2223])

In [13]:
inventory / 2

array([19.5, 19.5, 46.5, 43. , 24. , 23. , 24. , 15. ,  5.5, 28.5])

In [16]:
price = (rng.random(10) * 10).round(2)
price

array([1.9 , 1.69, 4.74, 5.92, 4.25, 8.22, 3.8 , 0.22, 9.82, 5.5 ])

In [17]:
price * inventory

array([ 74.1 ,  65.91, 440.82, 509.12, 204.  , 378.12, 182.4 ,   6.6 ,
       108.02, 313.5 ])

In [18]:
(price * inventory).sum()

np.float64(2282.59)

In [19]:
inventory_list = list(inventory)
inventory_list

[np.int64(39),
 np.int64(39),
 np.int64(93),
 np.int64(86),
 np.int64(48),
 np.int64(46),
 np.int64(48),
 np.int64(30),
 np.int64(11),
 np.int64(57)]

In [25]:
new_inventory = []

for x in inventory_list:
    new_inventory.append(int(x) + 2)

new_inventory

[41, 41, 95, 88, 50, 48, 50, 32, 13, 59]

In [26]:
[int(x) + 2 for x in inventory]

[41, 41, 95, 88, 50, 48, 50, 32, 13, 59]

In [ ]:
[round(float(x * y), 1) for x, y in zip(inventory_list, price)]

[74.1, 65.9, 440.8, 509.1, 204.0, 378.1, 182.4, 6.6, 108.0, 313.5]

---

## ASSIGNMENT 4: Array Operation

In [34]:
prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])

total = prices + 5
total

array([ 10.99,  11.99,  27.49, 104.99,   9.99,  54.99])

In [45]:
discount_pct = np.random.default_rng(2022).random(6).reshape(1, 6)
discount_pct

array([[0.24742606, 0.09299006, 0.61176337, 0.06066207, 0.66103343,
        0.75515778]])

In [46]:
pct_owed = 1 - discount_pct
pct_owed

array([[0.75257394, 0.90700994, 0.38823663, 0.93933793, 0.33896657,
        0.24484222]])

In [47]:
final_owed = np.round(pct_owed * total, 2)
final_owed

array([[ 8.27, 10.88, 10.67, 98.62,  3.39, 13.46]])