# WHERE FUNCTION

> The `where()` NumPy function peforms a logical test and returns a given value if the test is **True**, or another if the test is **False**.

In [1]:
import numpy as np

In [ ]:
inventory_array = np.array([12, 102, 18, 0, 0])

product_array = np.array(["fruits", "vegetables", "cereal", "dairy", "eggs"])

In [ ]:
np.where(inventory_array <= 0, "Out of Stock", "In Stock")

array(['In Stock', 'In Stock', 'In Stock', 'Out of Stock', 'Out of Stock'],
      dtype='<U12')

In [ ]:
# Methos 2: Complex Way
np.where(inventory_array <= 0, "Out of Stock", product_array)

array(['fruits', 'vegetables', 'cereal', 'Out of Stock', 'Out of Stock'],
      dtype='<U12')

---

## LABORATORY: Where Function

In [5]:
my_array = np.arange(20)
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
np.where(my_array % 2 == 0, "EVEN", "odd")

array(['EVEN', 'odd', 'EVEN', 'odd', 'EVEN', 'odd', 'EVEN', 'odd', 'EVEN',
       'odd', 'EVEN', 'odd', 'EVEN', 'odd', 'EVEN', 'odd', 'EVEN', 'odd',
       'EVEN', 'odd'], dtype='<U4')

In [ ]:
# Using double np.where()
np.where(my_array % 2 == 0, "EVEN", np.where(my_array == 9, my_array, "odd"))

array(['EVEN', 'odd', 'EVEN', 'odd', 'EVEN', 'odd', 'EVEN', 'odd', 'EVEN',
       '9', 'EVEN', 'odd', 'EVEN', 'odd', 'EVEN', 'odd', 'EVEN', 'odd',
       'EVEN', 'odd'], dtype='<U21')

In [ ]:
# Using double logical evaluation AND double np.where()
np.where(
    my_array % 2 == 0,
    "EVEN",
    np.where((my_array == 9) | (my_array == 3), my_array, "odd"),
)

array(['EVEN', 'odd', 'EVEN', '3', 'EVEN', 'odd', 'EVEN', 'odd', 'EVEN',
       '9', 'EVEN', 'odd', 'EVEN', 'odd', 'EVEN', 'odd', 'EVEN', 'odd',
       'EVEN', 'odd'], dtype='<U21')

In [21]:
# Provided array of ages
ages = np.array([25, 12, 15, 64, 35, 80, 45, 10, 22, 55])

In [ ]:
# Use NumPy's where function to find indices of ages that are 18 or older
adult_ages = np.where(ages >= 18)
adult_ages

(array([0, 3, 4, 5, 6, 8, 9]),)

---

# ASSIGNMENT 5: Filtering Arrays

>Filter the product array to only include those with prices greater than 25.
>
>Modify your logic to include 'cola', despite it not having a price greater than 25. Store the elements returned in an array called `fancy_feast_special`.
>
>Next, create a shipping cost array where the cost is 0 if price is greater than 20, and 5 if not.

In [ ]:
products = np.array(
    ["salad", "bread", "mustard", "rare tomato", "cola", "gourmet ice cream"]
)

prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])
print(products, prices)

['salad' 'bread' 'mustard' 'rare tomato' 'cola' 'gourmet ice cream'] [ 5.99  6.99 22.49 99.99  4.99 49.99]


In [ ]:
products[prices > 25]

array(['rare tomato', 'gourmet ice cream'], dtype='<U17')

In [ ]:
mask = (prices > 25) | (products == "cola")

fancy_feast_special = products[mask]
fancy_feast_special

array(['rare tomato', 'cola', 'gourmet ice cream'], dtype='<U17')

In [35]:
shipping_cost = np.where(prices > 20, 0, 5)
shipping_cost

array([5, 5, 0, 0, 5, 0])