---

# ARRAY AGGREGATION METHODS

---

In [1]:
import numpy as np

In [2]:
sales = np.array([[0, 5, 155, 0, 518], [0, 1827, 616, 317, 325]])
sales

array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]])

## Basic Aggregate Operations

In [3]:
sales.sum()

np.int64(3763)

In [4]:
sales.mean()

np.float64(376.3)

In [5]:
sales.max()

np.int64(1827)

In [6]:
sales.min()

np.int64(0)

## Aggregation Across Rows and Columns

In [7]:
sales

array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]])

In [8]:
sales.sum(axis=0)

array([   0, 1832,  771,  317,  843])

In [9]:
sales.sum(axis=1)

array([ 678, 3085])

In [10]:
sales.sum()

np.int64(3763)

## LABORATORY: Array Aggregations

In [11]:
rng = np.random.default_rng(616)

price = (rng.random(10) * 10).round(2)
price

array([3.97, 8.66, 4.6 , 3.06, 5.74, 0.89, 8.82, 7.32, 7.32, 5.62])

In [12]:
inventory = rng.integers(0, 100, 10)
inventory

array([80, 33, 60,  6, 31, 35, 16, 20, 29, 43])

In [13]:
inventory.mean()

np.float64(35.3)

In [14]:
inventory.std()

np.float64(20.48438429633656)

In [15]:
price * inventory

array([317.6 , 285.78, 276.  ,  18.36, 177.94,  31.15, 141.12, 146.4 ,
       212.28, 241.66])

In [ ]:
total_sales = price * inventory
total_sales_sum = total_sales.sum()
total_sales_sum

np.float64(1848.2900000000002)

In [22]:
total_sales_mean = total_sales.mean()
total_sales_mean

np.float64(184.829)

In [23]:
total_sales_max = total_sales.max()
total_sales_max

np.float64(317.6)

In [ ]:
# Index of the Max Value - "total_sales"
total_sales.argmax()

np.int64(0)

In [26]:
# Index of the Min Value - "total_sales"
total_sales.argmin()

np.int64(3)

In [ ]:
price_2d = price.reshape(5, 2)
price_2d

array([[3.97, 8.66],
       [4.6 , 3.06],
       [5.74, 0.89],
       [8.82, 7.32],
       [7.32, 5.62]])

In [29]:
# Sum across rows
price_2d.sum(axis=0)

array([30.45, 25.55])

In [30]:
# Sum across columns
price_2d.sum(axis=1)

array([12.63,  7.66,  6.63, 16.14, 12.94])