---

# VECTORIZATION & BROADCASTING

>`Vectorization` is the process of pushing array operations into optimized C code, which is easier and more efficient than writting **for loops**.


---





In [1]:
import numpy as np
import time

In [2]:
def for_loop_multiply_lists(list1, list2):
    product_list = []
    for elem1, elem2 in zip(list1, list2):
        product_list.append(elem1 * elem2)
    return product_list


def multiply_arrays(array1, array2):
    return array1 * array2

---

In [3]:
lst1 = list(range(1000))
lst2 = list(range(1000))

In [4]:
%%timeit -r 5 -n 10000
for_loop_multiply_lists(lst1, lst2)

20 µs ± 493 ns per loop (mean ± std. dev. of 5 runs, 10,000 loops each)


In [5]:
%%timeit
for_loop_multiply_lists(lst1, lst2)

19.9 µs ± 228 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


---

In [6]:
np_1 = np.array(lst1)
np_2 = np.array(lst2)

In [7]:
%%timeit -r 5 -n 10000
multiply_arrays(np_1, np_2)

491 ns ± 47.9 ns per loop (mean ± std. dev. of 5 runs, 10,000 loops each)


In [8]:
%%timeit
multiply_arrays(np_1, np_2)

421 ns ± 7.3 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


>`PRO TIP:`
>Use vectorized operations whenever possible when manipulating data, and avoid writing loops

---

# BROADCASTING

>`Broadcasting` lets you perform vectorized operations with arrays of different sizes, where NumPy will expand the smaller array to "fit" the larger one.

---



In [9]:
test_array = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
test_array

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

#### Example 1

In [10]:
# Braadcasting with a single number [1 x 1]
test_array + 1

array([[2, 3, 4],
       [2, 3, 4],
       [2, 3, 4]])

#### Example 2

In [11]:
# Broadcasting with a row [1 x 3]
test_array + np.array([3, 2, 1])

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

#### Example 3

In [12]:
# Broadcasting with a columns [3 x 1]
test_array + np.array([3, 2, 1]).reshape(3, 1)

array([[4, 5, 6],
       [3, 4, 5],
       [2, 3, 4]])

#### Example 4 (Error)

In [13]:
# Be careful with the size of each array. Becuase Broadcast can expand every randomly to fullfill blank spaces of an Array
test_array + np.array([2, 1])

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

#### Example 5

In [14]:
a = test_array[0, :]
b = test_array[:, 1]

print(f"Array a: {a}   -   Array b: {b}")

Array a: [1 2 3]   -   Array b: [2 2 2]


In [15]:
c = b.reshape(3, 1)
c

array([[2],
       [2],
       [2]])

In [16]:
# Example No. 4 - Sum rows with columns
a + c

array([[3, 4, 5],
       [3, 4, 5],
       [3, 4, 5]])

#### NOTE: Broadcasting can be implemented with 1D, 2D, 3D, nD

In [17]:
dim2 = np.ones((2, 3, 3), dtype=int)
dim2

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [18]:
dim1 = np.ones(3, dtype=int)
dim1

array([1, 1, 1])

In [19]:
result = dim1 + dim2
result

array([[[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]],

       [[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]]])

In [20]:
result.shape

(2, 3, 3)

In [21]:
np.ones((5, 1), dtype=int)

array([[1],
       [1],
       [1],
       [1],
       [1]])

---

# ASSIGNMENT: Vectorization & Broadcasting

---



In [22]:
import pandas as pd

In [23]:
retail_df = pd.read_csv(
    "Data/retail_2016_2017.csv", skiprows=range(1, 11000), nrows=1000
)
retail_df.sample(10)

,id,date,store_nbr,family,sales,onpromotion
936,1957879,2016-01-07,43,"LIQUOR,WINE,BEER",22.000,0
952,1957895,2016-01-07,44,BREAD/BAKERY,1016.513,1
698,1957641,2016-01-07,37,HOME AND KITCHEN I,21.000,0
108,1957051,2016-01-07,20,LADIESWEAR,2.000,0
508,1957451,2016-01-07,31,MAGAZINES,0.000,0
193,1957136,2016-01-07,23,BREAD/BAKERY,203.313,2
583,1957526,2016-01-07,33,SEAFOOD,3.000,0
188,1957131,2016-01-07,23,AUTOMOTIVE,2.000,0
113,1957056,2016-01-07,20,MEATS,471.233,24
240,1957183,2016-01-07,24,LADIESWEAR,17.000,0


In [24]:
family_array = np.array(retail_df["family"])
sales_array = np.array(retail_df["sales"])

print(f"Length of Family Array: {len(family_array)}")

Length of Family Array: 1000


In [25]:
produce_array = sales_array[family_array == "PRODUCE"]
print(f'Total length of "produce_array": {len(produce_array)}\n')
produce_array

Total length of "produce_array": 30



array([1662.394,  447.064, 2423.944,  962.866, 1236.404,  298.441,
       1077.44 , 3404.531,  962.96 ,  279.505, 1852.786, 1089.319,
        726.516, 7860.031,  446.038, 1155.385,  120.202,  862.092,
        473.952,  254.263, 1272.755, 2775.771, 2030.762, 1657.432,
       2339.906,  722.333, 1567.843, 2458.456,  673.885, 8834.15 ])

In [26]:
rng = np.random.default_rng(2022)

random_array = rng.random(30)
random_array

array([0.24742606, 0.09299006, 0.61176337, 0.06066207, 0.66103343,
       0.75515778, 0.1108689 , 0.04305584, 0.41441747, 0.98862926,
       0.96919869, 0.25697153, 0.55876211, 0.24234798, 0.32202029,
       0.89135975, 0.94611366, 0.72253931, 0.92847437, 0.99608701,
       0.2494223 , 0.06229007, 0.94479027, 0.65028587, 0.32167568,
       0.08336384, 0.21924361, 0.08417791, 0.05213927, 0.20525022])

In [27]:
produce_sample = produce_array[random_array < 0.5]
print(f'Total length of "produce_sample": {len(produce_sample)}\n')
produce_sample

Total length of "produce_sample": 17



array([1662.394,  447.064,  962.866, 1077.44 , 3404.531,  962.96 ,
       1089.319, 7860.031,  446.038, 1272.755, 2775.771, 2339.906,
        722.333, 1567.843, 2458.456,  673.885, 8834.15 ])

In [28]:
mean = produce_sample.mean()
mean

np.float64(2268.102470588235)

In [29]:
median = np.median(produce_sample)
median

np.float64(1272.755)

In [30]:
np.where(
    produce_sample < median,
    "below_both",
    np.where(produce_sample > mean, "above_both", "above_median"),
)

array(['above_median', 'below_both', 'below_both', 'below_both',
       'above_both', 'below_both', 'below_both', 'above_both',
       'below_both', 'above_median', 'above_both', 'above_both',
       'below_both', 'above_median', 'above_both', 'below_both',
       'above_both'], dtype='<U12')

---

# KEY TAKEAWAYS

---

>1. `Numpy forms the foundation for Pandas`: 
>   - It's important to be comfortable working with NumPy arrays & functions in order to use Pandas data structurres & functions properly
>
>
>2. `Numpy arrays are more efficient than base Python lists and tuples`:
>   - They are semimutable data structures capable of storing many data types
>   - Their values can be modified, but their size cannot
>
>
>3. `Array operations let you aggregate, filter and sort data`:
>   - Broadcasting and Vectorization make these operations convenient and efficient without the use of loops
>   - The syntax for NumPy array operations is very similar to Pandas
